export type Page =
  | "home"
  | "gallery"
  | "archive"
  | "news"
  | "shop"
  | "about"
  | "contact"
  | "studio"
  | "book";

export interface Work {
  id: string;
  title: string;
  year: number;
  category: string;
  technique: string;
  image: string;
  description: string;
  span?: "wide" | "tall" | "normal";
}

export interface NewsItem {
  id: string;
  title: string;
  date: string;
  month: string;
  year: number;
  image: string;
  excerpt: string;
  tag: string;
  gallery?: { image: string; name: string; available: boolean }[];
}

export interface Product {
  id: string;
  name: string;
  price: number;
  category: string;
  edition: string;
  image: string;
  description: string;
  sizes?: string[];
  available: boolean;
}

export const works: Work[] = [
  {
    id: "0056",
    title: "Nosferatu",
    year: 2026,
    category: "Tatuaje",
    technique: "Realismo",
    image: "/works/nosferatu.mp4",
    description: "Retrato del Conde Orlok inspirado en Nosferatu, en realismo blanco y negro",
    span: "normal",
  },
  {
    id: "0001",
    title: "Charmander",
    year: 2023,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/charmander.jpeg",
    description: "Tatuaje de Charmander en color completo",
    span: "tall",
  },
  {
    id: "0002",
    title: "Samurai",
    year: 2025,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/Samurai.mp4",
    description: "Tatuaje de samurái en blackwork",
    span: "wide",
  },
  {
    id: "0003",
    title: "Perrito Naranja",
    year: 2026,
    category: "Tatuaje",
    technique: "Neo-traditional",
    image: "/works/perrito.mp4",
    description: "Tatuaje de perrito naranja en neo-traditional",
    span: "normal",
  },
  {
    id: "0004",
    title: "Santa Muerte",
    year: 2026,
    category: "Tatuaje",
    technique: "Sombras",
    image: "/works/muerte.mp4",
    description: "Tatuaje de la Santa Muerte trabajado en sombras y claroscuro, explorando la frontera entre la vida y la muerte.",
    span: "tall",
  },
  {
    id: "0005",
    title: "Diptico vida y muerte",
    year: 2024,
    category: "Tatuaje",
    technique: "Realismo",
    image: "/works/skull.mp4",
    description: "representacion de la dualidad humana parte 2.",
    span: "wide",
  },
  {
    id: "0006",
    title: "Diptico de vida y muerte parte 1",
    year: 2024,
    category: "Tatuaje",
    technique: "Realismo",
    image: "/works/Vida.mp4",
    description: "Representacion de la dualidad humana parte 1.",
    span: "normal",
  },
  {
    id: "0007",
    title: "Daga",
    year: 2025,
    category: "Tatuaje",
    technique: "Sombras",
    image: "/works/daga.mp4",
    description: "Tatuaje de daga en sombras",
    span: "normal",
  },
  {
    id: "0008",
    title: "Soledad",
    year: 2026,
    category: "Tatuaje",
    technique: "Lettering",
    image: "/works/Soledad.mp4",
    description: "Letras y sombra ",
    span: "normal",
  },
  {
    id: "0009",
    title: "Puñal",
    year: 2025,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/Puñal.mp4",
    description: "Tatuaje de puñal",
    span: "normal",
  },
  {
    id: "0010",
    title: "Carnero",
    year: 2026,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/carnero.mp4",
    description: "Tatuaje de carnero",
    span: "normal",
  },
  {
    id: "0011",
    title: "Escudo de Legend of Zelda",
    year: 2022,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/escudodelegendofzelda.jpg",
    description: "Escudo Hylian",
    span: "normal",
  },
  {
    id: "0012",
    title: "Golondrina",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/golondrina.mp4",
    description: "Tatuaje de golondrina",
    span: "normal",
  },
  {
    id: "0013",
    title: "Hongo",
    year: 2021,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/hongo.jpg",
    description: "Tatuaje de hongo",
    span: "normal",
  },
  {
    id: "0014",
    title: "Mapache",
    year: 2026,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/mapache.mp4",
    description: "Tatuaje de mapache",
    span: "normal",
  },
  {
    id: "0015",
    title: "Máscara 1",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/mascara1.mp4",
    description: "Tatuaje de máscara",
    span: "normal",
  },
  {
    id: "0016",
    title: "Máscara 2",
    year: 2025,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/mascara2.mp4",
    description: "Tatuaje de máscara",
    span: "normal",
  },
  {
    id: "0017",
    title: "Mujer Afro",
    year: 2026,
    category: "Tatuaje",
    technique: "Realismo",
    image: "/works/mujerafro.mp4",
    description: "Tatuaje de retrato",
    span: "normal",
  },
  {
    id: "0018",
    title: "Rosa",
    year: 2025,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/rosa.mp4",
    description: "Tatuaje de rosa",
    span: "normal",
  },
  {
    id: "0019",
    title: "Serpiente 1",
    year: 2025,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/serpiente1.mp4",
    description: "Tatuaje de serpiente",
    span: "normal",
  },
  {
    id: "0020",
    title: "Serpiente 2.1",
    year: 2022,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/serpiente2.1.jpg",
    description: "Detalle de serpiente",
    span: "normal",
  },
  {
    id: "0021",
    title: "Serpiente 2",
    year: 2022,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/serpiente2.jpg",
    description: "Tatuaje de serpiente",
    span: "normal",
  },
  {
    id: "0022",
    title: "Spiderman",
    year: 2023,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/spiderman.jpg",
    description: "Tatuaje de Spiderman",
    span: "normal",
  },
  {
    id: "0023",
    title: "Carlitos",
    year: 2022,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/carlitos.jpg",
    description: "Tatuaje de Carlitos (Rugrats) en color completo",
    span: "normal",
  },
  {
    id: "0024",
    title: "Cráneo de Cuervo",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/craneo-cuervo.jpeg",
    description: "Cráneo de cuervo con plumas, en blackwork con sombreado degradado",
    span: "normal",
  },
  {
    id: "0025",
    title: "Cuervo",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/cuervo.jpeg",
    description: "Cuervo en vuelo sobre el dorso de la mano, en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0026",
    title: "Daga Personalizada",
    year: 2023,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/daga-personalizada.jpeg",
    description: "Daga personalizada con cráneo y cuernos de cabra, en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0027",
    title: "David",
    year: 2022,
    category: "Tatuaje",
    technique: "Realismo",
    image: "/works/david.jpeg",
    description: "Retrato en realismo del David de Miguel Ángel",
    span: "normal",
  },
  {
    id: "0028",
    title: "Dragón Japonés",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/dragon-japones.jpeg",
    description: "Dragón japonés con peonías y nubes, en blackwork",
    span: "normal",
  },
  {
    id: "0029",
    title: "Gárgola",
    year: 2023,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/gargola.jpeg",
    description: "Gárgola alada sobre una taza, en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0030",
    title: "Gato Japonés",
    year: 2023,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/gato-japones.jpeg",
    description: "Gato y dragón japonés en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0031",
    title: "Gato Maestro",
    year: 2023,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/gato-maestro.jpeg",
    description: "Gato maestro con pipa y motivos japoneses, en color completo",
    span: "normal",
  },
  {
    id: "0032",
    title: "Gato Realista",
    year: 2022,
    category: "Tatuaje",
    technique: "Realismo",
    image: "/works/gato-realista.jpeg",
    description: "Retrato realista de gato con líneas de boceto",
    span: "normal",
  },
  {
    id: "0033",
    title: "Gato",
    year: 2022,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/gato-sphynx.jpeg",
    description: "Gato esfinge estilizado con collar de tachuelas, en blackwork",
    span: "normal",
  },
  {
    id: "0034",
    title: "Goku",
    year: 2023,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/goku.jpeg",
    description: "Goku Super Saiyan de Dragon Ball, en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0035",
    title: "Kempachi",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/kempachi.jpeg",
    description: "Personajes de anime en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0036",
    title: "León Realista",
    year: 2023,
    category: "Tatuaje",
    technique: "Realismo",
    image: "/works/leon-realista.jpg",
    description: "Retrato realista de león con ojos en color, sobre el dorso de la mano",
    span: "normal",
  },
  {
    id: "0037",
    title: "Máscara de Kitsune",
    year: 2023,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/mascara-kitsune.jpg",
    description: "Máscara de kitsune con peonías, en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0038",
    title: "Máscara Oni Cartoon",
    year: 2023,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/mascara-oni-cartoon.jpeg",
    description: "Máscara oni estilo cartoon, en color completo",
    span: "normal",
  },
  {
    id: "0039",
    title: "Máscara Oni Roja",
    year: 2023,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/mascara-oni-roja.jpeg",
    description: "Máscara oni roja tradicional, en color completo",
    span: "normal",
  },
  {
    id: "0040",
    title: "Memento Mori",
    year: 2023,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/memento-mori.jpg",
    description: "Manos alcanzándose con un ojo, inspirado en 'La Creación de Adán', en blackwork",
    span: "normal",
  },
  {
    id: "0041",
    title: "Ojo Neotradicional",
    year: 2024,
    category: "Tatuaje",
    technique: "Neo-traditional",
    image: "/works/ojo-neotradicional.jpeg",
    description: "Ojo neotradicional con formas de hoja, en color",
    span: "normal",
  },
  {
    id: "0042",
    title: "Panda",
    year: 2023,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/panda.jpeg",
    description: "Panda rojo sosteniendo una máscara oni, en color completo",
    span: "normal",
  },
  {
    id: "0043",
    title: "Peonía Japonesa",
    year: 2022,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/peonia-japonesa.jpeg",
    description: "Peonía japonesa en color completo",
    span: "normal",
  },
  {
    id: "0044",
    title: "Peonía en la Mano",
    year: 2023,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/peonia-mano.mp4",
    description: "Peonía en blackwork con dotwork, sobre el dorso de la mano",
    span: "normal",
  },
  {
    id: "0045",
    title: "Rana",
    year: 2023,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/rana.jpeg",
    description: "Rana arborícola en color completo",
    span: "normal",
  },
  {
    id: "0046",
    title: "Rosa en la Espalda",
    year: 2025,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/rosa-espalda.jpg",
    description: "Rosa con hojas en blackwork con dotwork, sobre la espalda",
    span: "normal",
  },
  {
    id: "0047",
    title: "Sinji de Evangelion",
    year: 2021,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/sinji-evangelion.jpeg",
    description: "Escena de Shinji Ikari (Neon Genesis Evangelion), en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0048",
    title: "Squirtle",
    year: 2022,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/squirtle.jpeg",
    description: "Squirtle de Pokémon en color completo",
    span: "normal",
  },
  {
    id: "0049",
    title: "Vegeta",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/vegeta.jpeg",
    description: "Vegeta y Trunks de Dragon Ball, en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0050",
    title: "Zarigueya",
    year: 2026,
    category: "Tatuaje",
    technique: "Color",
    image: "/works/zarigueya.jpeg",
    description: "Zarigüeya colgando de una rama con fresas, en color completo",
    span: "normal",
  },
  {
    id: "0051",
    title: "Zorrito",
    year: 2021,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/zorrito.jpeg",
    description: "Zorro entre flores, en blackwork con dotwork",
    span: "normal",
  },
  {
    id: "0052",
    title: "Carpas Koi",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/carpas-koi.mp4",
    description: "Dos carpas koi en composición circular, en blackwork",
    span: "normal",
  },
  {
    id: "0053",
    title: "Devil May Cry I",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/devil-may-cry-1.mp4",
    description: "Personaje alado inspirado en Devil May Cry, en blackwork",
    span: "normal",
  },
  {
    id: "0054",
    title: "Devil May Cry II",
    year: 2024,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/devil-may-cry-2.mp4",
    description: "Demonio alado inspirado en Devil May Cry, en blackwork",
    span: "normal",
  },
  {
    id: "0055",
    title: "Golondrina",
    year: 2022,
    category: "Tatuaje",
    technique: "Blackwork",
    image: "/works/golondrina-2022.jpeg",
    description: "Golondrina en vuelo sobre el dorso de la mano, en blackwork con dotwork",
    span: "normal",
  },
];

export const newsItems: NewsItem[] = [
  {
    id: "flash-coleccion-agosto",
    title: "Nueva Serie ''Valores''",
    date: "Agosto 2026",
    month: "AGO",
    year: 2026,
    image: "/news/serie-valores-honor.jpg",
    excerpt: "Nueva colección de flash inspirada en valores y virtudes, cada diseño acompañado de una cita filosófica. Nueve piezas disponibles para agendar, consulta disponibilidad.",
    tag: "Flash",
    gallery: [
      { image: "/news/serie-valores-fe.jpg", name: "Fe", available: true },
      { image: "/news/serie-valores-gratitud.jpg", name: "Gratitud", available: true },
      { image: "/news/serie-valores-honor.jpg", name: "Honor", available: true },
      { image: "/news/serie-valores-paciencia.jpg", name: "Paciencia", available: true },
      { image: "/news/serie-valores-sabiduria.jpg", name: "Sabiduría", available: true },
      { image: "/news/serie-valores-lealtad.jpg", name: "Lealtad", available: true },
      { image: "/news/serie-valores-perseverancia.jpg", name: "Perseverancia", available: true },
      { image: "/news/serie-valores-disciplina.jpg", name: "Disciplina", available: true },
      { image: "/news/serie-valores-honestidad.jpg", name: "Honestidad", available: true },
    ],
  },
];

export const products: Product[] = [
  {
    id: "gorra-cafe-pana",
    name: "Gorra Café (Pana)",
    price: 50000, 
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-cafe-pana.jpg",
    description: "Gorra bordada Osiris en pana",
    available: true,
  },
  // ── Disponibles (fuente: carpeta "Gorras_disponibles") ──────────────────
  {
    id: "gorra-negra",
    name: "Gorra Negra",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-negra.jpg",
    description: "Gorra bordada Osiris",
    available: true,
  },
  {
    id: "gorra-azul",
    name: "Gorra Azul",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-azul.jpg",
    description: "Gorra bordada Osiris",
    available: true,
  },
  {
    id: "gorra-cafe",
    name: "Gorra Café",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-cafe.jpg",
    description: "Gorra bordada Osiris",
    available: true,
  },
  {
    id: "gorra-blanca",
    name: "Gorra Blanca",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-blanca.jpg",
    description: "Gorra bordada Osiris",
    available: true,
  },
  {
    id: "gorra-crema",
    name: "Gorra Crema (Gamuza)",
    price: 45000,
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-crema.jpg",
    description: "Gorra bordada Osiris en gamuza",
    available: true,
  },
  {
    id: "gorra-kaki",
    name: "Gorra Kaki",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-kaki.jpg",
    description: "Gorra bordada Osiris",
    available: true,
  },

  // ── No disponibles / agotadas (fuente: carpeta "Gorras_no_disponibles") ─
  {
    id: "gorra-nu-metal",
    name: "Gorra Nu-Metal",
    price: 68000,
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-roja.jpg",
    description: "Gorra bordada Osiris",
    available: false,
  },
  {
    id: "gorra-mostaza-pana",
    name: "Gorra Mostaza (Pana)",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-mostaza-pana.jpg",
    description: "Gorra bordada Osiris en pana",
    available: false,
  },
  {
    id: "gorra-vinotinto-pana",
    name: "Gorra Vinotinto (Pana)",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-vinotinto-pana.jpg",
    description: "Gorra bordada Osiris en pana",
    available: false,
  },
  {
    id: "gorra-kaki-negra",
    name: "Gorra Kaki (Letras Negras)",
    price: 50000, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-kaki-negra.jpg",
    description: "Gorra bordada Osiris",
    available: true,
  },
  
  {
    id: "gorra-negra-pana",
    name: "Gorra Negra (Pana)",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-negra-pana.jpg",
    description: "Gorra bordada Osiris en pana",
    available: false,
  },
  {
    id: "gorra-rosa",
    name: "Gorra Rosa",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-rosa.jpg",
    description: "Gorra bordada Osiris",
    available: false,
  },
  {
    id: "gorra-verde-petroleo-pana",
    name: "Gorra Verde Petróleo (Pana)",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-verde-petroleo-pana.jpg",
    description: "Gorra bordada Osiris en pana",
    available: false,
  },
  {
    id: "gorra-verde-oliva-pana",
    name: "Gorra Verde Oliva (Pana)",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-verde-oliva-pana.jpg",
    description: "Gorra bordada Osiris en pana",
    available: false,
  },
  {
    id: "gorra-cafe-desgastado",
    name: "Gorra Café Desgastado",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-cafe-desgastado.jpg",
    description: "Gorra bordada Osiris",
    available: false,
  },
  {
    id: "gorra-negra-denim",
    name: "Gorra Negra (Denim)",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-negra-denim.jpg",
    description: "Gorra bordada Osiris en denim",
    available: false,
  },
  {
    id: "gorra-camel-pana",
    name: "Gorra Camel (Pana)",
    price: 0, // PRECIO PENDIENTE — editar manualmente
    category: "Ropa",
    edition: "3ra serie de gorras",
    image: "/shop/gorra-camel-pana.jpg",
    description: "Gorra bordada Osiris en pana",
    available: false,
  },
];

export const archiveYears: Record<number, Work[]> = {
  2026: works.filter((w) => w.year === 2026),
  2025: works.filter((w) => w.year === 2025),
  2024: works.filter((w) => w.year === 2024),
  2023: works.filter((w) => w.year === 2023),
  2022: works.filter((w) => w.year === 2022),
  2021: works.filter((w) => w.year === 2021),
};

export const galleryCategories = ["Todas", "Tatuaje", "Arte", "Ilustración", "Diseño", "Proyectos", "Dibujo"];

export const formatCOP = (price: number) =>
  price > 0
    ? new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(price)
    : "Precio a definir";
